name: 'Fetch and parse .env from repo'
description: 'Clone another repository, extract the properties.env file and convert it to JSON.'
author: 'Varomegar'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  repo:
    description: 'Name of your repo (e.g. your-org/target-repo)'
    required: true
  ref:
    description: 'Branch of youyrselectedd repo (e.g. main)'
    required: true
  github_token:
    description: 'GitHub Token with read permissions'
    required: true
  env_path:
    description: 'Rute to properties.env'
    required: false
    default: 'properties.env'

outputs:
  env-json:
    description: 'Content of properties.env converted to JSON'
    value: ${{ steps.parse.outputs.env-json }}

runs:
  using: "composite"
  steps:
    - name: Clone Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo }}
        token: ${{ inputs.github_token }}
        ref: ${{ inputs.ref }}
        path: target-repo

    - name: Parse properties.env to JSON
      id: parse
      shell: bash
      run: |
        ENV_PATH="target-repo/${{ inputs.env_path }}"
        if [[ ! -f "$ENV_PATH" ]]; then
          echo "❌ No se encontró el archivo: $ENV_PATH"
          exit 1
        fi
        json="{"
        while IFS='=' read -r key val || [ -n "$key" ]; do
          [[ -z "$key" || "$key" == \#* ]] && continue
          key=$(echo "$key" | xargs)
          val=$(echo "$val" | sed -e 's/^["'\'']//;s/["'\'']$//' | xargs)
          val=$(printf '%s' "$val" | sed 's/"/\\"/g')
          json+="\"$key\":\"$val\","
        done < "$ENV_PATH"
        json="${json%,}}"
        echo "Generated content: $json"
        echo "env-json=$json" >> "$GITHUB_OUTPUT"
